// Copy for the public build gallery (/builds) and the Builder's publish dialog,
// in every supported language. Class order matches the `class` index stored
// in the database (worker/index.ts): never reorder, only append.
import type { Language } from '../constants/translations';

export const CLASS_NAMES: Record<Language, string[]> = {
  en: ['Feca', 'Osamodas', 'Enutrof', 'Sram', 'Xelor', 'Ecaflip', 'Eniripsa', 'Iop', 'Cra', 'Sadida', 'Sacrier', 'Pandawa', 'Rogue', 'Masqueraider', 'Ouginak', 'Foggernaut', 'Eliotrope', 'Huppermage'],
  fr: ['Féca', 'Osamodas', 'Enutrof', 'Sram', 'Xélor', 'Ecaflip', 'Eniripsa', 'Iop', 'Crâ', 'Sadida', 'Sacrieur', 'Pandawa', 'Roublard', 'Zobal', 'Ouginak', 'Steamer', 'Eliotrope', 'Huppermage'],
  es: ['Feca', 'Osamodas', 'Anutrof', 'Sram', 'Xelor', 'Zurcarák', 'Aniripsa', 'Yopuka', 'Ocra', 'Sadida', 'Sacrógrito', 'Pandawa', 'Tymador', 'Zobal', 'Ouginak', 'Steamer', 'Selotrop', 'Hipermago'],
  pt: ['Feca', 'Osamodas', 'Enutrof', 'Sram', 'Xelor', 'Ecaflip', 'Eniripsa', 'Iop', 'Cra', 'Sadida', 'Sacrier', 'Pandawa', 'Roublard', 'Zobal', 'Ouginak', 'Steamer', 'Eliotrope', 'Huppermage'],
};

const en = {
  title: 'Community Builds',
  subtitle: 'Browse equipment builds shared by other players, open them in the Builder and publish your own.',
  tabBuilder: 'Builder',
  tabGallery: 'Community builds',
  sortNew: 'Newest',
  sortTop: 'Most liked',
  allClasses: 'All classes',
  allLevels: 'All levels',
  search: 'Search a build or author…',
  by: (author: string) => `by ${author}`,
  anonymous: 'anonymous',
  level: 'Lvl',
  open: 'Open in Builder',
  like: 'Like',
  report: 'Report',
  reportConfirm: 'Report this build as inappropriate? Builds reported by several players are hidden.',
  reported: 'Thanks, the build has been reported.',
  loadMore: 'Load more',
  noMatch: 'No builds match these filters.',
  empty: 'No builds yet. Be the first to publish one from the Builder!',
  unavailable: 'The gallery is not available right now. Please try again later.',
  shared: 'Shared build',
  // publish dialog (Builder)
  publish: 'Publish',
  publishTitle: 'Publish this build',
  publishIntro: 'Your build will be visible to everyone in the Community builds gallery.',
  name: 'Build name',
  namePlaceholder: 'e.g. Iop tank 230',
  author: 'Your name (optional)',
  className: 'Class',
  noClass: '— none —',
  description: 'Description (optional)',
  descriptionPlaceholder: 'Playstyle, sublimations, tips…',
  submit: 'Publish',
  cancel: 'Cancel',
  published: 'Build published!',
  viewInGallery: 'View in the gallery',
  copyLink: 'Copy link',
  tooMany: 'You published many builds in the last hour. Please try again later.',
  publishError: 'Publishing failed. Please try again.',
  emptyBuild: 'Equip at least one item before publishing.',
  rules: 'Keep names and descriptions respectful: reported builds are hidden.',
};

export type BuildGalleryT = typeof en;

const fr: BuildGalleryT = {
  title: 'Builds de la communauté',
  subtitle: "Parcourez les builds partagés par d'autres joueurs, ouvrez-les dans le Créateur et publiez les vôtres.",
  tabBuilder: 'Créateur',
  tabGallery: 'Builds de la communauté',
  sortNew: 'Plus récents',
  sortTop: 'Plus aimés',
  allClasses: 'Toutes les classes',
  allLevels: 'Tous les niveaux',
  search: 'Rechercher un build ou un auteur…',
  by: (author) => `par ${author}`,
  anonymous: 'anonyme',
  level: 'Niv.',
  open: 'Ouvrir dans le Créateur',
  like: "J'aime",
  report: 'Signaler',
  reportConfirm: 'Signaler ce build comme inapproprié ? Les builds signalés par plusieurs joueurs sont masqués.',
  reported: 'Merci, le build a été signalé.',
  loadMore: 'Voir plus',
  noMatch: 'Aucun build ne correspond à ces filtres.',
  empty: 'Aucun build pour le moment. Soyez le premier à en publier un depuis le Créateur !',
  unavailable: "La galerie n'est pas disponible pour le moment. Réessayez plus tard.",
  shared: 'Build partagé',
  publish: 'Publier',
  publishTitle: 'Publier ce build',
  publishIntro: 'Votre build sera visible par tous dans la galerie des builds de la communauté.',
  name: 'Nom du build',
  namePlaceholder: 'ex. Iop tank 230',
  author: 'Votre nom (facultatif)',
  className: 'Classe',
  noClass: '— aucune —',
  description: 'Description (facultatif)',
  descriptionPlaceholder: 'Style de jeu, sublimations, conseils…',
  submit: 'Publier',
  cancel: 'Annuler',
  published: 'Build publié !',
  viewInGallery: 'Voir dans la galerie',
  copyLink: 'Copier le lien',
  tooMany: 'Vous avez publié beaucoup de builds dans la dernière heure. Réessayez plus tard.',
  publishError: 'La publication a échoué. Veuillez réessayer.',
  emptyBuild: 'Équipez au moins un objet avant de publier.',
  rules: 'Restez respectueux dans les noms et descriptions : les builds signalés sont masqués.',
};

const es: BuildGalleryT = {
  title: 'Builds de la comunidad',
  subtitle: 'Explora builds compartidas por otros jugadores, ábrelas en el Creador y publica las tuyas.',
  tabBuilder: 'Creador',
  tabGallery: 'Builds de la comunidad',
  sortNew: 'Más recientes',
  sortTop: 'Más gustadas',
  allClasses: 'Todas las clases',
  allLevels: 'Todos los niveles',
  search: 'Buscar una build o un autor…',
  by: (author) => `por ${author}`,
  anonymous: 'anónimo',
  level: 'Nv.',
  open: 'Abrir en el Creador',
  like: 'Me gusta',
  report: 'Denunciar',
  reportConfirm: '¿Denunciar esta build como inapropiada? Las builds denunciadas por varios jugadores se ocultan.',
  reported: 'Gracias, la build ha sido denunciada.',
  loadMore: 'Ver más',
  noMatch: 'Ninguna build coincide con estos filtros.',
  empty: 'Todavía no hay builds. ¡Sé el primero en publicar una desde el Creador!',
  unavailable: 'La galería no está disponible en este momento. Inténtalo más tarde.',
  shared: 'Build compartida',
  publish: 'Publicar',
  publishTitle: 'Publicar esta build',
  publishIntro: 'Tu build será visible para todos en la galería de builds de la comunidad.',
  name: 'Nombre de la build',
  namePlaceholder: 'p. ej. Yopuka tanque 230',
  author: 'Tu nombre (opcional)',
  className: 'Clase',
  noClass: '— ninguna —',
  description: 'Descripción (opcional)',
  descriptionPlaceholder: 'Estilo de juego, sublimaciones, consejos…',
  submit: 'Publicar',
  cancel: 'Cancelar',
  published: '¡Build publicada!',
  viewInGallery: 'Ver en la galería',
  copyLink: 'Copiar enlace',
  tooMany: 'Has publicado muchas builds en la última hora. Inténtalo más tarde.',
  publishError: 'No se pudo publicar. Inténtalo de nuevo.',
  emptyBuild: 'Equipa al menos un objeto antes de publicar.',
  rules: 'Sé respetuoso en nombres y descripciones: las builds denunciadas se ocultan.',
};

const pt: BuildGalleryT = {
  title: 'Builds da comunidade',
  subtitle: 'Explore builds compartilhadas por outros jogadores, abra-as no Criador e publique as suas.',
  tabBuilder: 'Criador',
  tabGallery: 'Builds da comunidade',
  sortNew: 'Mais recentes',
  sortTop: 'Mais curtidas',
  allClasses: 'Todas as classes',
  allLevels: 'Todos os níveis',
  search: 'Buscar uma build ou autor…',
  by: (author) => `por ${author}`,
  anonymous: 'anônimo',
  level: 'Nv.',
  open: 'Abrir no Criador',
  like: 'Curtir',
  report: 'Denunciar',
  reportConfirm: 'Denunciar esta build como inadequada? Builds denunciadas por vários jogadores são ocultadas.',
  reported: 'Obrigado, a build foi denunciada.',
  loadMore: 'Ver mais',
  noMatch: 'Nenhuma build corresponde a esses filtros.',
  empty: 'Ainda não há builds. Seja o primeiro a publicar uma pelo Criador!',
  unavailable: 'A galeria não está disponível no momento. Tente novamente mais tarde.',
  shared: 'Build compartilhada',
  publish: 'Publicar',
  publishTitle: 'Publicar esta build',
  publishIntro: 'Sua build ficará visível para todos na galeria de builds da comunidade.',
  name: 'Nome da build',
  namePlaceholder: 'ex. Iop tanque 230',
  author: 'Seu nome (opcional)',
  className: 'Classe',
  noClass: '— nenhuma —',
  description: 'Descrição (opcional)',
  descriptionPlaceholder: 'Estilo de jogo, sublimações, dicas…',
  submit: 'Publicar',
  cancel: 'Cancelar',
  published: 'Build publicada!',
  viewInGallery: 'Ver na galeria',
  copyLink: 'Copiar link',
  tooMany: 'Você publicou muitas builds na última hora. Tente novamente mais tarde.',
  publishError: 'Falha ao publicar. Tente novamente.',
  emptyBuild: 'Equipe pelo menos um item antes de publicar.',
  rules: 'Seja respeitoso nos nomes e descrições: builds denunciadas são ocultadas.',
};

export const BUILD_GALLERY_T: Record<Language, BuildGalleryT> = { en, fr, es, pt };

/** Level brackets offered as a filter: [min, max]. */
export const LEVEL_BRACKETS: [number, number][] = [
  [1, 50], [51, 100], [101, 140], [141, 185], [186, 215], [216, 230], [231, 245],
];
